# peterdd: I use it with vagrant plugin 'hostsupdater'

Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "ldap.example.com"
  config.vm.network "private_network", ip: "10.0.0.38"

  config.vm.provision "shell", path: "provision.sh"
end
